<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import needed library
import pandas as pd

In [2]:
# Set file location
fileLocation = "https://github.com/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Proramming/blob/main/AMZN.csv?raw=true"

In [4]:
# Connect to and load data from a file
# Example: .CSV file
dfRaw = pd.read_csv(fileLocation)

In [5]:
# Preview the top 5 rows of the loaded data
dfRaw.head()

,Date,Low,Open,Volume,High,Close,Adjusted Close
0,15-05-1997,0.096354,0.121875,1443120000,0.125000,0.097917,0.097917
1,16-05-1997,0.085417,0.098438,294000000,0.098958,0.086458,0.086458
2,19-05-1997,0.081250,0.088021,122136000,0.088542,0.085417,0.085417
3,20-05-1997,0.081771,0.086458,109344000,0.087500,0.081771,0.081771
4,21-05-1997,0.068750,0.081771,377064000,0.082292,0.071354,0.071354

In [6]:
# Preview the last 5 rows of the loaded data
dfRaw.tail()

,Date,Low,Open,Volume,High,Close,Adjusted Close
6433,06-12-2022,87.900002,90.500000,75503600,91.040001,88.250000,88.250000
6434,07-12-2022,87.480003,88.339996,68086900,89.889999,88.459999,88.459999
6435,08-12-2022,87.879997,89.239998,73305900,90.860001,90.349998,90.349998
6436,09-12-2022,88.629997,88.900002,67316900,90.300003,89.089996,89.089996
6437,12-12-2022,87.870003,89.209999,19174427,89.500000,88.455002,88.455002

In [7]:
# Preview the top n rows of the loaded data
n = 3
dfRaw.head(n)

,Date,Low,Open,Volume,High,Close,Adjusted Close
0,15-05-1997,0.096354,0.121875,1443120000,0.125000,0.097917,0.097917
1,16-05-1997,0.085417,0.098438,294000000,0.098958,0.086458,0.086458
2,19-05-1997,0.081250,0.088021,122136000,0.088542,0.085417,0.085417

In [8]:
# Preview the last n rows of the loaded data
n = 3
dfRaw.tail(n)

,Date,Low,Open,Volume,High,Close,Adjusted Close
6435,08-12-2022,87.879997,89.239998,73305900,90.860001,90.349998,90.349998
6436,09-12-2022,88.629997,88.900002,67316900,90.300003,89.089996,89.089996
6437,12-12-2022,87.870003,89.209999,19174427,89.500000,88.455002,88.455002

In [10]:
# Preview a sample row from the loaded data
dfRaw.sample()

           Date       Low  Open     Volume    High     Close  Adjusted Close
471  30-03-1999  3.788281   3.8  523548000  4.2375  4.117188        4.117188

In [11]:
# Preview sample n rows of the loaded data
n = 7
dfRaw.sample(n)

,Date,Low,Open,Volume,High,Close,Adjusted Close
5291,24-05-2018,79.418999,79.901497,68600000,80.412003,80.153503,80.153503
4689,04-01-2016,31.375500,32.814499,186290000,32.886002,31.849501,31.849501
3017,13-05-2009,3.700500,3.812500,175410000,3.832500,3.709500,3.709500
2589,30-08-2007,3.915000,3.920000,92576000,4.005500,3.934000,3.934000
6039,14-05-2021,159.149994,159.278000,66500000,161.442993,161.145004,161.145004
5305,14-06-2018,85.443497,85.674004,63488000,86.239998,86.193001,86.193001
2528,05-06-2007,3.543000,3.555000,608850000,3.712000,3.682500,3.682500

In [12]:
# Get the shape of the dataframe (rows and columns)
dfRaw.shape

(6438, 7)