<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import needed library
import pandas as pd

In [2]:
# Set file location
fileLocation = "https://github.com/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Proramming/blob/main/daily_sales_items_top105.parquet?raw=true"

In [3]:
# Connect to and load data from a file
# Example: .PARQUET file
dfRaw = pd.read_parquet(fileLocation)

In [4]:
# Preview the top 5 rows of the loaded data
dfRaw.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
7,HOBBIES_1_008_CA_1_evaluation,HOBBIES_1_008,HOBBIES_1,HOBBIES,CA_1,CA,489,12,2012-05-31
14,HOBBIES_1_015_CA_1_evaluation,HOBBIES_1_015,HOBBIES_1,HOBBIES,CA_1,CA,489,11,2012-05-31
47,HOBBIES_1_048_CA_1_evaluation,HOBBIES_1_048,HOBBIES_1,HOBBIES,CA_1,CA,489,0,2012-05-31
98,HOBBIES_1_103_CA_1_evaluation,HOBBIES_1_103,HOBBIES_1,HOBBIES,CA_1,CA,489,2,2012-05-31
173,HOBBIES_1_178_CA_1_evaluation,HOBBIES_1_178,HOBBIES_1,HOBBIES,CA_1,CA,489,3,2012-05-31

In [ ]:
# Preview the last 5 rows of the loaded data
dfRaw.tail()

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
59180900,FOODS_3_635_WI_3_evaluation,FOODS_3_635,FOODS_3,FOODS,WI_3,WI,990,0,2013-10-14
59180959,FOODS_3_694_WI_3_evaluation,FOODS_3_694,FOODS_3,FOODS,WI_3,WI,990,40,2013-10-14
59180978,FOODS_3_714_WI_3_evaluation,FOODS_3_714,FOODS_3,FOODS,WI_3,WI,990,16,2013-10-14
59180987,FOODS_3_723_WI_3_evaluation,FOODS_3_723,FOODS_3,FOODS,WI_3,WI,990,43,2013-10-14
59181070,FOODS_3_808_WI_3_evaluation,FOODS_3_808,FOODS_3,FOODS,WI_3,WI,990,0,2013-10-14

In [ ]:
# Preview the top n rows of the loaded data
n = 3
dfRaw.head(n)

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
7,HOBBIES_1_008_CA_1_evaluation,HOBBIES_1_008,HOBBIES_1,HOBBIES,CA_1,CA,489,12,2012-05-31
14,HOBBIES_1_015_CA_1_evaluation,HOBBIES_1_015,HOBBIES_1,HOBBIES,CA_1,CA,489,11,2012-05-31
47,HOBBIES_1_048_CA_1_evaluation,HOBBIES_1_048,HOBBIES_1,HOBBIES,CA_1,CA,489,0,2012-05-31

In [ ]:
# Preview the last n rows of the loaded data
n = 3
dfRaw.tail(n)

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
59180978,FOODS_3_714_WI_3_evaluation,FOODS_3_714,FOODS_3,FOODS,WI_3,WI,990,16,2013-10-14
59180987,FOODS_3_723_WI_3_evaluation,FOODS_3_723,FOODS_3,FOODS,WI_3,WI,990,43,2013-10-14
59181070,FOODS_3_808_WI_3_evaluation,FOODS_3_808,FOODS_3,FOODS,WI_3,WI,990,0,2013-10-14

In [ ]:
# Preview a sample row from the loaded data
dfRaw.sample()

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
709375,FOODS_2_181_CA_3_evaluation,FOODS_2_181,FOODS_2,FOODS,CA_3,CA,344,24,2012-01-07

In [ ]:
# Preview sample n rows of the loaded data
n = 7
dfRaw.sample(n)

,id,item_id,dept_id,cat_id,store_id,state_id,d,value,date
26574846,FOODS_3_587_TX_2_evaluation,FOODS_3_587,FOODS_3,FOODS,TX_2,TX,1557,38,2015-05-04
50272651,HOUSEHOLD_1_179_WI_2_evaluation,HOUSEHOLD_1_179,HOUSEHOLD_1,HOUSEHOLD,WI_2,WI,1797,19,2015-12-30
33409409,HOUSEHOLD_2_421_WI_1_evaluation,HOUSEHOLD_2_421,HOUSEHOLD_2,HOUSEHOLD,WI_1,WI,1265,0,2014-07-16
7425317,HOUSEHOLD_1_447_TX_2_evaluation,HOUSEHOLD_1_447,HOUSEHOLD_1,HOUSEHOLD,TX_2,TX,461,0,2012-05-03
13109721,FOODS_2_244_WI_3_evaluation,FOODS_2_244,FOODS_2,FOODS,WI_3,WI,1713,1,2015-10-07
54741615,FOODS_3_694_CA_4_evaluation,FOODS_3_694,FOODS_3,FOODS,CA_4,CA,1201,10,2014-05-13
37457862,HOUSEHOLD_1_339_TX_2_evaluation,HOUSEHOLD_1_339,HOUSEHOLD_1,HOUSEHOLD,TX_2,TX,1642,3,2015-07-28

In [ ]:
# Get the shape of the dataframe (rows and columns)
dfRaw.shape

(2038050, 9)